sushiro is updated

diff --git a/sushiro b/sushiro
--- a/sushiro
+++ b/sushiro
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# sushiro 0.0.4
+# sushiro 0.0.5
 # (C) 2018 redpeacock78
 # GPLv3 is applied to this script
 
@@ -23,7 +23,7 @@
 
 ###USAGE###
 [[ "${1}" = "-h" ]] && \
-	printf "sushiro version 0.0.4\n\nUSAGE: sushiro [OPTIONS] [ANYTHING]\nOptions:\n -l [NUMBER]\n    Randomly display the number of specified menus\n    (By default it display one item)\n -p [MENU_NAME]\n    Display price of menu corresponding to name\n    (If not specified,all menus and prices will be displayed)\n -k [MENU_NAME]\n    Display the calorie of the name corresponding menu\n    (If not specified,all menus and calories are displayed)\n -a\n    Display names of all menus(158 species in total)\n -f\n    Fetch menus from www.akindo-sushiro.co.jp\n    (The menu will be saved in /usr/local/share/sushiro_cache)\n" && \
+	printf "sushiro version 0.0.5\n\nUSAGE: sushiro [OPTIONS] [ANYTHING]\nOptions:\n -l [NUMBER]\n    Randomly display the number of specified menus\n    (By default it display one item)\n -p [MENU_NAME]\n    Display price of menu corresponding to name\n    (If not specified,all menus and prices will be displayed)\n -k [MENU_NAME]\n    Display the calorie of the name corresponding menu\n    (If not specified,all menus and calories are displayed)\n -a\n    Display names of all menus(158 species in total)\n -f\n    Fetch menus from www.akindo-sushiro.co.jp\n    (The menu will be saved in /usr/local/share/sushiro_cache)\n" && \
 exit 0
 
 
@@ -94,7 +94,7 @@ while [[ "${#}" -gt 0 ]]; do
       | sort \
       | uniq \
       | sed 's/,倍/倍/' \
-      | grep "${CALORIES}" \
+      | gr!!ep "${CALORIES}" \
       | awk -F ',' '{print $1,$3}' \
       | sed 's/ 100円+税//' \
       | grep "\S"
@@ -112,6 +112,12 @@ while [[ "${#}" -gt 0 ]]; do
       | awk -F, 'NR>1{print $1}' \
       | grep "\S" && \
       exit 0
+  else
+     printf "sushiro: missing operand\nTry 'sushiro -h' for more information.\n" && \
+     exit 2
   fi
 done
 
+[[ -n  "${#}" ]] && \
+  printf "sushiro: missing operand\nTry 'sushiro -h' for more information.\n" && \
+exit 2
